/**
 * @author Vincent Moudy
 */
define([], function() {'use strict';
	var x, y, z, w, v;
	x = Math.floor(Math.random() * 10);
	y = Math.floor(Math.random() * 10);
	z = Math.floor(Math.random() * 10);
	w = Math.floor(Math.random() * 10);
	v = Math.floor(Math.random() * 10);
	
    return {
        origin : ["#begin#"],
		begin : ["#enroute# #recon#", "#during# #secrecy# #mission# #recon2#", "We #engaged# #fight#", "#decided# #curiosity#"],
		decided : ["We decided to check out", "When passing by", "A routine fly-by by", "Readings from"],
		during : ["During", "While on", "On", " Amidst", "In the midst of", "Midway through"],
		enroute : ["On our way", "En route", "Travelling", "Headed for", "In transit", "On the way"],
		location : ["the #spaceClouds# nebula", "the #stars# star cluster", "the planet #planetName#"],
		location2 : ["zone #num#", "#stars# system", "sector #alphabet#"],
		quad : ["#section# quadrant"],
		objects : "star asteroid meteor quasar satellite planet".split(" "),
		
		planetName : ["Abadeen", "Adelphous IV", "Akrayde VII", "Aldron IV", "Deravin V", "Emila II", "Gailen IV", "Garon II", "Harrod IV", "Hogas II", "Iratin V", "Kabatris", "Kataan", "Keeair", "Kling", "Ligon II", "Lyar", "Malkus IX", "Marlonia", "Minas V", "Norphin V", "Pentarus II", "Phendouse V", "Qualar II", "Ramantis III", "Risa", "Sarona VIII", "Tarella", "Tessen II", "Titus IV", "Valo I", "Ventax II", "Zalcon"],
		spaceClouds : "Crab Carina Eagle Flame Omega Horsehead Orion Hourglass Tarantula Helix".split(" "),
		recon : ["to the #quad#, #next#", "to #location#, #next#"],
		recon2 : ["through the #quad#, #next#", "to #location2#, #next#"],
		stars : ["Pleiades", "Hyades", "Beehive", "Poppy", "Foxtail", "Leviathan", "Heretic", "Akmar", "Kawkab", "Khepri", "Celesse", "Realta", "Urania", "Helia", "Elektra", "Indu", "Tenshi", "Acidalia", "Oriana", "Gimle", "Aymelek", "Seren"],
		
		fight : ["when our ship was hit by #enemy.a# #shipWeapon#. #hit#", "where we #battlePasttense# #enemy.a# #shipEnemyType#. #mix#", " and moved into position when #reinforcements#"],
		mix : ["It turned out to be an ambush. #ambush#", "The #battle# didn't last too long. #counter#"],
		hit : ["We were able to fire #num# #rounds# before we had to take cover behind #planetName.s# moon, #stars#. #thruster#", "Our shields took most of the damage. #counter#"],
		counter : ["When the enemy realized they couldn't score a direct hit, they decided to take cover behind #planetName#. We pursued the target and I hailed their Captain; I wanted to negotiate or face #total# #annihilation#. Their #response#"],
		response : ["was a mistake, they were delaying while arming their #shipWeapon# but wasn't soon enough. I fired our #shipWeapon# that #annihilated# any and all possible threats.", "was suspect but when we sent the away team, they put down their arms and surrendered without trouble. After interrogating their Captain, they informed me they are a recon team on the fore front of a massive attack against the Federation. We transferred the prisoners to #planetName# and passed word to the Vice Admiral who is starting a counter offensive."],
		thruster : ["Our main thrusters were down but were soon up again if not for the great work by our chief engineer. We quickly maneuvered into firing position and fired #num# #rounds#. They were able to escape the barrage and disappeared somewhere in the #spaceClouds# nebula. We will be conducting a recon mission there tomorrow.", " #thrusterDown#"],
		thrusterDown : ["With out main thrust, the only thing to do was divert power to shields and call for reinforcements. [u:#uss#] The USS #u# quickly responded to our request and was several minutes away. Taking more hits, if the #u# hadn't shown up then, starfleet would have been short one ship by the end of the day. The #u# #did#"],
		did : ["#annihilated# the threat and sent over some engineers to help repair our thrusters. We are heading to #stars# space station to transfer over our badly wounded and resupply.", "was able to #disable# the enemy ship, they have taken prisoners and are interrogating them now. #escort#"],
		escort : ["They towed us back to a repair station in #spaceClouds# system for resupplies and repairs.", "They offered to send over their chief engineer to help get our engines back online. We are now headed to begin our #mission# in the #quad#."],
		rounds : ["bursts", "rounds", "torpedoes", "lasers", "missiles"],
		curiosity : ["[s:#soil#]planet #planetName# and #found# anomalies in the planets #s#. I sent an away team to investigate and this is their report: \"Upon further investigation into the anomaly, we found that planets #s# #report2#"],
		report2 : ["is undergoing abnormal evolution. #evolution#", "is experiencing rapid change. #rapid#", "is entering its final phase in its life. #dying#"],
		evolution : ["We took some readings by the planets deep sea vents and found that its temperature is ."+v+" warmer that the previous tests. Some flora and fauna on the planet have also disappeared since the last survey team was here. We Have advised the Captain to inform the Federation and to keep a close eye on this planet.\""],
		rapid : ["This planet is a part of the Federation so we went right to the board of leaders. They informed us that #aware#", "This planet is not part of the Federation and is not inhabited. #strange#", "This planet is inhabited but not apart of the Federation. #situ#"],
		situ : ["We sent the #searchTeam# in order to not break the Prime Directive. #situ2#", "Not violating the Prime Directive, we observed from high orbit. #situ2#", "We made our observations from high orbit not to be detected or interfere. #situ2#"],
		situ2 : ["We came across a interesting species. They thrive on a warmer planet. Even though they have little surface water, their bodies do not require like ours. They have machinery to keep the planets core hotter than normal to survive. I have logged the planets coordinates and designated them Species "+x+y+z+w+".\"", "Our observations indicate a species who have reached a high intellectual state but lack technology or resources; they're seem heavenly or supernatural in nature. The rising planet temperature doesn't seem to affect them and it doesn't appear that they need food or water to keep their \"bodies\" moving.\"", "#situ3#"],
		situ3 : ["We found a primordial species similar to the ones on #planetName#. They don't even have a chance against the planets changing systems. Honestly, I don't even think they have any clue on what's going on other than there own primal instincts of eating and breeding.\""],
		strange : ["[e:#enemy#]But the away team reported back that there was #e# technology forming the world to meet their habitable needs. Apparently, something went wrong with the geothermal converter and caused the planets core to accelerate and causing #e# engineers to abandoned their project.\"", "The amount of CO2 and other gasses are increasing in an exponential amount, something that Venus went through in the Sol system. Thankfully its not inhabited and intellectual life will be lost.\""],
		dying : ["The planet is experiencing an effect similar to #planetName# or Venus in the Sol system, a run away green house effect.\"", "Apparently, a humanoid species abused its use of fossil fuels on the planet which caused the planets eco-system to crash. First the ozone that warmed the planet and its oceans. That changed its weather patterns in such a way that any life, flora or fauna, could not be sustained. Pitty...\"", "Like #planetName#, this planet has been around for some #years#. Its star, #stars#, is also dying which might be the cause of this planet withering as well. We informed the Federation as a no-fly zone with a looming supernova.\""],
		years : ["five hundred million", "seven hundred million", "one billion", "three hundred million", "two hundred fifty million", "eight hundred million"],
		aware : ["they are aware of the change and have a survey team investigating the situation now. #aware2#", "the are not aware of the situation and are willing to corporate to give us full access to their resources. #notAware#"],
		notAware : ["Apparently, the change on the planet has been affecting their understanding and thinking capabilities. We've put an immediate request with the Federation to help the planet maintain balance.\"", "Upon further observation, we noticed that the people were acting very strange. Not a care in the world. Our analysis determined that the gases escaping from the core were at fault. #solve#"],
		solve : ["It triggered a chemical release in their brains similar to consuming alcohol or drugs. There doesn't seem a way to fix the problem so we have ordered an immediate evacuation with assistance from Starfleet or face the consequence of #annihilation#", "It triggered a chemical release in their brains similar to consuming alcohol or drugs. We advised Starfleet command and they sent over engineers and survey teams to slow down this effect.\""],
		aware2 : ["We rendezvoused with the team to figure out what's going on. They informed us that a few months back they started to drill deeper in hopes of filling their dwindling supply of plasma fuel. #plasma#", "We tried to meet up with the team but the board of leaders aggressively shooed us off and assured us that everything is fine, nothing out of the ordinary. #weird#"],
		plasma : ["We informed them that this was dangerous and is similar to what happened on #planetName#. They said the were taking all precautions and that we have nothing to worry about. I suggest keeping a Federation advisor on the planet.\"", "We told them that #planetName# experimented with the same technique and resulted in the #annihilation# of the indigenous population, flora and fauna. We also informed that if they need more fuel, to contact Federation Plasma Fuel Supply Agency and they can supply some at a discounted price. Still waiting for response.\""],
		weird : ["After briefing the Captain, we sent a #searchTeam# to uncover the strange truth. They found that they are working with the #enemy# and developing a weapon capable of bringing the Federation to its knees. #inform#", "Are working on some kind of worm hole, time travelling technology with the motive of taking over the Federation when it was small and weak in the past. #inform#"],
		inform :["We informed the Federation and the Vice Admiral is spear heading an all out assault on the planet and nearby stations.\"", "We informed the Federation and they have cut off funding, removed the Planet from the Federation, and are considering their options on what to do next.\""],
		soil : ["soil", "atmosphere", "air", "crust", "ocean"],
		battlePasttense : ["engaged with", "opened fire on", "immediately opened fire on", "made contact with", "released a barrage upon"],
		reinforcements : ["#enemy# reinforcements ambushed us from our flank. #ambush#", "[u:#uss#]the USS #u# #appeared2# behind #planetName.s# moon, #stars#. We moved into attack position when the #u# #when#"],
		ambush : ["We hailed any and all Federation ships in the sector for immediate reinforcements; #retreat#", "We hailed any and all Federation ships in the sector for immediate reinforcements. #fight2#", "Without any other Federation starship nearby, outnumbered, and flanked, #retreat#"],
		retreat : ["I ordered a tactical retreat to the nearest friendly controlled station in the #stars# system. #retreat2#", "with no other option other than total destruction of the ship and all life on board lost, we left for the nearest friendly space station by planet #planetName#. #retreat2#", "I fired #num# blast at the enemy directly in front to cover our retreat to the #spaceClouds# nebula to regroup with Federation starfleet. #retreat2#"],
		retreat2 : ["I logged the coordinates and have put together a small team of star ships for a counter-attack. #retreat3#", "I passed the coordinates to command, they have assembled a squadron to counter-attack and our ship will take lead. #retreat3#", "Command wanted the position of the attack and will set an ambush with a squadron of my choice, I have assembled USS's #uss#, #uss#, and #uss#. #retreat3#"],
		retreat3 : ["The attack was very successful with minimal damage. We destroyed or #disabled# #num# #shipEnemyType.s#. I will pass the news to command and put in medal requests for the participating star ships", "The attack was met with #heavy# resistance. After the #battle# was over we lost #half# ships, however, we served a #critical# blow to the enemy fleet. Our comrades will not have died in vain.", "The enemy strength was greater than we first thought, we lost all but two, including us, to enemy forces and one ship as POW's. We are regrouping at planet #planetName# space station where the Vice-Admiral will personally lead an aggressive counter attack."],
		fight2 : ["[u1:#uss#][u2:#uss#] USS #u1# and USS #u2# responded and informed me they were a quick jump away. The #u1# flanked port and the #u2# came from above. The enemy ship, predicting its doom, launched escape pods that us and #u2# picked up. #transport#", "[u1:#uss#][u2:#uss#] The USS #u1# and USS #u2# came to our assistance but unfortunately, we lost #u1# when trying to #disable# the enemy ship. Some pods managed to escape but more than #half# lives were lost. Enemy presence is not detected in that system."],
		transport : ["We transferred them to the nearest Federation space station, station #alphabet#, and are being debriefed.", "After the enemy ship was #annihilated#, we picked up some of the pods but when the away team boarded, they put up a fight. We lost #num# ensigns and #num# were wounded.", "Some pods managed to get away but the others that stayed, were #annihilated# by the other USS starship; I have requested a court martial for their captain. This kind of act with not be tolerated in the Federation", "The pods escaped and the other star ship followed them to the #quad#. They were all capture their according to the Captain's loFg."],
		half : ["half", "quarter", "third", "two", "three", "four"],
		uss : ["Saratoga", "Sentinel", "Galaxy", "Odyssey", "Challenger", "Venture", "Yamato", "Valley Forge", "Excelsior", "Fearless", "Nova", "Equinox"],
		appeared2 : ["appeared from", "came from,", "showed up from"],
		when : ["took #num# hits, one of them #critical#, striking the bridge. #fatal#", "took #num# hits but were able to fire their #shipWeapon#. #foughtBack#", "fired their #shipWeapon# which #disabled# the enemies ability to move. #surrounded#"],
		surrounded : ["We quickly surrounded the vessel, and asked for an immediate surrender. At first, there wasn't a response, then they hailed back and said they would rather die then surrender. Their ship self destructed and inflicted #heavy# damage to our ships. We were able to get patched up at #stars# station.", "Surrounded and out numbered, they gave themselves and their ship up to the Federation. We haven't heard from them sense, they were taken to the #quad# for \"interrogation\" but no on has heard from them sense then."],
		foughtBack : ["They fought gallantly, dealing many #critical# blows to the enemy ship. Unfortunately, their reactors took a #critical# hit that led to the inevitable destruction of the ship.", "They were able to provide covering fire while we retreated back to the #spaceClouds# nebula to regroup and reassess. All souls perished.", "They were able to provide covering fire while we maneuvered into a better firing position, we fired our #shipWeapon# that delivered a #critical# blow. We sent over or chiefs medical and engineer to help their wounded and get their reactors back online."],
		critical : ["critical", "tragic", "disastrous", "catastrophic", "fatal", "calamitous"],
		fatal : ["We then countered attacked with our #shipWeapon#, causing the enemies main weapon to go off-line. #fatal2#", "We then countered attacked with our #shipWeapon#, causing the enemies engines to go off-line. #fatal3#"],
		fatal2 : ["We delivered #critical.a# blow from our #shipWeapon# and took the enemy out once and for all.", "I hailed the crew and asked for their surrender, #then#"],
		then : ["they laughed at the thought and set a crash course for our ship. I ordered another barrage that was #critical# and stopped the threat.", "With no other option, they laid down their weapons and powered down. #IGo# the task of rounding up the prisoners, all #fifty# of them will be held on station #alphabet#, the Federation will decide what to do with them."],
		fatal3 : ["They countered with their #shipWeapon#, which #disabled# our main thrusters. Two ships with out the ability to maneuver, #locked# each other, armed and ready, #fired#"],
		fired :["they fired first. We fired counter-measures and released our photon torpedo which was a #critical# strike. No survivors; #shipProblems#", "we fired first but they countered with their plasma torpedo. #help#", "both of us fired"],
		help : ["[u:#uss#]I guess we weren't alone after all, the USS #u# picked up the other ship's distress signal. The #u# fire #num# torpedoes on the enemy. No survivors; #u# used their tractor beam to tow us back to #alphabet# station in the #stars# cluster for repairs.", "[u:#uss#]I guess we weren't alone after all, the USS #u# picked up the other ship's distress signal. The #u# sent to homing torpedoes to intercept the incoming rounds which gave us enough time to rearm that served #critical# blow needed to eliminate the threat. The #u# sent #help3#"],
		help3 : ["some engineers to help get us repaired. Once operational, we will head to the #quad#.", "their chief engineer to get us operational again. I have put in a request for a medal for their bravery and heroism."],
		locked : ["locked on", "staring at", "focused on"],
		heavy : ["heavy", "minimal", "some", "great"],
		
		num : "two three four five six seven".split(" "),
		alphabet : "alpha bravo charley delta echo kilo lima quebec sierra tango".split(" "),
		size : "huge small average colossal gigantic enormous minute".split(" "),
		section : "alpha beta gamma delta".split(" "),
		color :  "red blue green yellow purple black brown white".split(" "),
		
		enemy : ["Borg", "Klingon", "Romulan", "Cardassians", "Dominion", "Breen"],
		shipEnemyType : ["starship", "warship", "cruiser", "destroyer", "patrol ship", "carrier", "battle cruiser", "interceptor"],
		engaged : ["spotted an enemy while a conducting a #secrecy# #mission# in the #quad#", "ran into an enemy in #location2#", "stumbled upon an enemy by planet #planetName#", "were conducting a search and destroy patrol by #location#"],
		disabled : ["disabled", "heavily damaged", "wrecked", "damaged"],
		disable : ["disable", "destroy", "damage", "immobilize", "knock out"],
		shipWeapon : ["phase cannon", "plasma cannon", "pulse cannon", "disrupter", "plasma torpedo", "gravimetric torpedo"],
		IGo : ["I went with", "I accompanied", "I led", "I tagged along with"],
		greetings : ["to greet", "to address", "to meet", ],
		strangers : ["strangers", "friends", "species"],
		galaxy : ["Andromeda", "Black Eye", "Triangulum", "Sombrero", "Pinwheel", "Sunflower", "Tadpole", "Whirlpool", "Centaurus A"],
		
		report : ["reported to me ", "gave me", "informed me", "briefed me"],
		news : "great ghastly excellent intriguing curious splendid horrible".split(" "),
		typeOfNews : ["really #news#", "absolutely #news#", "just #news#", "completely #news#"],
		found : ["came across", "stumbled upon", "discovered", "found", "detected", "identified", "encountered"],
		alien : ["artifact", "starship", "space station"],
		condition : ["derelict", "desolated", "abandoned"],
		investigate : ["investigate", "search", "inspect", "examine", "explore", "probe"],
		foundAdj : ["peculiar", "strange", "interesting", "unusual", "mysterious", "inexplicable"],
		breaking : ["breaking", "breaching", "violating", "disobeying"],
		foundWhat : ["life on planet #planetName#. Although the life is quiet advance, they don't appear to have warp capabilities. #cont#", "#condition.a# spaceship not from this galaxy. #continue1#", "an alien species #cataloged#. I hailed them and requested to board; they complied. #etProblem2#","#disabled.a# spaceship #unfamiliar#. I scanned this ship for life, detected some, then hailed them to come aboard. They said #etProblem#"],
		cont : ["Without #breaking# the Prime Directive, we sent in our #searchTeam# to #investigate#, what we classified as Species "+x+y+z+w+", what they found was a species like humans of earth who are around what is equivalent to earth's 21 century.#cont2#"],
		cont2 : ["#thisWay#", "#orThatWay#"],
		thisWay : ["#assumption# that Species "+x+y+z+w+" has come together as one, stopped using harmful fossil fuels, and will most likely enter Warp capabilities #soon#. I will inform the Federation of their advancement and to have Species "+x+y+z+w+" watched and ready to be apart of the Federation."],
		orThatWay : ["The team #report# of their intel that their survival as a species looks #lookBad#; the only outcome is #outcome#."],
		outcome : ["mass genocide, leaving the planet only a few cultures or one culture to rule. They control fear and resources and quickly silent dissent and progressive thinkers. A Narrow minded society, never being able to achieve never being able to reach Warp status", "#total# #annihilation# of all species, leaving the planet inhabitable from constant fighting stemming from the inability to compromise and open their minds and accept culture differences.", "sending the species back to the stone age. A result from greed, corruption, and ignorance of their place on their planet and in the Universe."],
		continue1 : ["We sent an away team to #investigate# the ship. They reported back that the ship's #etProblem3#."],
		etProblem : ["there black mater-hyper-drive converter was sabotaged by an enemy spy. #continue3#", "there warp drive was #disabled# from a #battle# with unknown aggressors. They informed the team that this unknown assailant then headed to the #stars# system in the #quad# after their starship was damaged. #continue2#"],
		etProblem2 : ["#IGo# the away team #greetings# these new #strangers# personally. They were #friendly# when we boarded and when asked where they are from, they replied that they are from what we call the #galaxy# galaxy. #butHow#"],
		butHow : ["Looking at their Captain's log, it appears they were conducting #secrecy# patrol in their #quad# when they #iSee#"],
		iSee : ["lost power and drifted into a worm hole. #andThen#", "were ambushed by an enemy #otherEnemy# that ruptured their warp drive and created a black hole that the ship fell into. #andThen2#"],
		andThen : ["They came out the other side here in our galaxy but over in the #stars# system. They have been #travelling# around, #looking# for a way back home. I #extended# the assistance of the Federation and that the closet station is in zone #num#."],
		andThen2 : ["When the hole opened up, they crew thought that was the end. They #theyCame# by our galactic core and have been #travelling# without power for sometime. We used our tractor beam tow their ship back to #alphabet# station where the Federation will take over."],
		etProblem3 : ["The ship has a remarkable resemblance to the #galaxyClass# class star ships but constructed of different materials not known in this galaxy. Their logs were destroyed and we were able to tow the ship back to space station #alphabet#", "The ships log say its a Starfleet ship belonging to the Wells-Class. I have found no records past or present on Wells-Class ships. Starfleet is as confused as we are on this ship."],
		continue2 : ["Their ship has been a drift for awhile and we have dispatched our chief engineer to help with their warp #warp#. We gave them some supplies to help their wounded and sick. #finale#"],
		continue3 : ["We sent our chief engineer but was unsuccessful since he was completely confused with the internal workings of a black matter-hyper-drive converter. We were able to tow their ship to the #alphabet# system where they are docked at station #alphabet#. #finale#"],
		finale: ["#interested# was the size of their ship and the type of engine flying that thing. When questioned by my first officer, they said, and their computer agreed, they were from this galaxy, however, they mentioned that everything is different, that they are apart of a #republic#..."],
		republic : ["Republic of Planets", "United Planets", "Alliance of Democratic Planets", "League of Planets"],
		appeared : ["appeared", "we assumed", "we presumed"],
		next : ["we #found# what #appeared# to be #foundWhat#"],
		department : ["chief engineer #report# some #engineerProblems#", "away team", "security officer #report# some #shipProblems#", "chief medical officer #report# some #medProblems#", "first officer #report# some #engineerProblems#"],
		assumption : ["It appears", "It seems", "We can assume without doubt", "It's highly probable"],
		friendly : ["friendly", "cooperative", "non-hostile"],
		secrecy : ["a top secret", "a routine", "a normal", "a military"],
		mission : ["mission", "reconnaissance", "patrol", "surveillance"],
		otherEnemy : ["star fleet", "starship", "cruiser", "dreadnought", "warship", "star destroyer"],
		travelling : ["travelling", "cruising", "floating", "drifting"],
		looking : ["looking", "searching", "seeking", "exploring"],
		extended : ["extended", "gave", "offered"],
		lookBad : ["grim", "bleak", "somber", "forlorn", "helpless"],
		theyCame : ["came out", "emerged by", "appeared by", "showed up", "arrived by", "materialized by"],
		warp : ["drive", "engines", "reactors", "power", "capabilities"],
		interested : ["What I was interested in was", "What I wanted to know was", "The one thing that #rouse# my curiosity was"],
		rouse : ["roused", "spiked", "provoked", "stirred", "raised"],
		searchTeam : ["Stealth Infiltrating Team", "Special Secretive Intelligence Team", "Deep Cover Operatives", "Intelligence Investigative Squad", "Advance Recon on Primitive Species Team"],
		soon : ["soon", "very soon", "within the next few centuries", "within a few decades", "at the turn of the century", "approximately #fifty# cycles from now."],
		fifty : ["fifty", "thirty", "eighty", "forty-two", "twenty", "seventy-six", "twenty-two", "thirty-nine", "eighty-eight", "ninety"],
		total : ["total", "mass", "complete", "utter", "entire", "outright", "full", "thorough"],
		annihilation : ["annihilation", "destruction", "eradication", "extinction", "elimination"],
		annihilated : ["annihilated", "destroyed", "eradicated", "eliminated"],
		unfamiliar : ["unknown to me or my crew", "not registered with the Federation", "not of origin from the four quadrants", "that I couldn't determine place of origin", "type I haven't seen before", "that left me clueless"],
		cataloged : ["unfamiliar to me", "not on any Federation records", "not in any records aboard this ship", "that me or the crew knew of", "that is registered with the Federation"],
		battle : ["fight", "battle", "engagement", "skirmish", "clash", "conflict", "encounter", "assault"],
		galaxyClass : ["Galaxy", "Nova", "Excelsior", "Sovereign"],
		
		order : "recommend order advise suggest direct".split(" ")
		
		
    };
});
